sudo: required
services:
  - docker

before_install:
  - docker build -t kblan017/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run kblan017/react-test npm test -- --coverage 

after_success:
  - docker build -t kblan017/multi-client ./client
  - docker build -t kblan017/multi-nginx ./nginx
  - docker build -t kblan017/multi-server ./server
  - docker build -t kblan017/multi-worker ./worker
  #log in to the docker cli 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # take those images and push them to docker-hub

  - docker push kblan017/multi-client 
  - docker push kblan017/multi-nginx
  - docker push kblan017/multi-server
  - docker push kblan017/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-415193239432
  bucket_path: docker-multi
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



